FROM jeremycurny/php-magento2:7.0-fpm-stretch

MAINTAINER "Jeremy CURNY" <jeremy.curny.pro@gmail.com>

ARG DEBIAN_FRONTEND=noninteractive

ENV MAGENTO_PUB_KEY 6c7c3956d991c6459bcbf6d0d977514f
ENV MAGENTO_PRI_KEY 2319f30adac6169a5c30ad2cb564d177

ENV MAGENTO_PROJECT magento/project-community-edition=2.3.0
