#!/bin/bash -e

if [[ $# -ne 1 ]]; then
  echo "Illegal number of parameters"
  exit 1
fi

find $1 -type f -exec chmod 640 {} \;	
find $1 -type d -exec chmod 750 {} \;	
find $1/app/etc -type d -exec chmod 770 {} \;	
find $1/app/etc -type f -exec chmod 660 {} \;	
find $1/generated -type d -exec chmod 770 {} \;	
find $1/generated -type f -exec chmod 660 {} \;	
find $1/pub/media -type d -exec chmod 770 {} \;	
find $1/pub/media -type f -exec chmod 660 {} \;	
find $1/pub/static -type d -exec chmod 770 {} \;	
find $1/pub/static -type f -exec chmod 660 {} \;	
find $1/var -type d -exec chmod 770 {} \;	
find $1/var -type f -exec chmod 660 {} \;
