#!/bin/bash -e

if [[ $# -ne 3 ]]; then
  echo "Illegal number of parameters"
  exit 1
fi

PROJECT=$1
VERSION=$2
ARTIFACT_NAME=$3

rm -rf $TMP_DECK && mkdir -p $TMP_DECK
composer create-project --no-progress --repository-url=https://repo.magento.com/ $PROJECT=$VERSION $TMP_DECK
rm -rf $TMP_DECK/vendor

chown -R www-data:www-data $TMP_DECK

tar -czf $ARTIFACT_PATH/$ARTIFACT_NAME -C $TMP_DECK .
rm -rf $TMP_DECK && mkdir -p $TMP_DECK
